--[[
  build.lua -- l3build configuration for hithesis

  Harbin Institute of Technology Thesis Template

  Targets
    l3build unpack          unpack hithesis.dtx into build/unpacked
    l3build doc             typeset hithesis.pdf (XeLaTeX, CJK)
    l3build install         install runtime files into TEXMFHOME
    l3build install --full  also install documentation and sources
    l3build ctan            build the CTAN archive (hithesis-ctan.zip)
    l3build upload          validate / upload the archive to CTAN
    l3build tag <ver>       bump the version + date in hithesis.dtx
    l3build clean           remove the build directory
]]

-- Package identity
module = "hithesis"

-- The documentation loads CJK fonts, so it must be typeset with XeLaTeX
typesetexe  = "xelatex"
typesetopts = "-interaction=nonstopmode"

-- Runtime files extracted by hithesis.ins and installed into tex/latex/hithesis/
-- (.sty covers dtx-style.sty, which is only needed while typesetting the docs)
installfiles = {"*.cls", "*.sty", "*.cfg", "*.eps"}

-- BibTeX styles -> bibtex/bst/hithesis/, MakeIndex styles -> makeindex/hithesis/
bstfiles       = {"*.bst"}
makeindexfiles = {"*.ist"}

-- dtx-style.sty is a documentation-only style: keep it out of the installed
-- runtime tree. It is still available to `l3build doc` via the local build tree.
excludefiles = {"*~", "build.lua", "config-*.lua", "dtx-style.sty"}

-- Sources shipped on CTAN (placed in source/latex/hithesis/)
sourcefiles = {"hithesis.dtx", "hithesis.ins"}

-- Text documentation shipped on CTAN (placed in doc/latex/hithesis/)
textfiles  = {"README.md"}
ctanreadme = "README.md"

-- Treat the vector graphics as binary when creating archives
binaryfiles = {"*.eps"}

-- Also ship a ready-made TDS archive (hithesis.tds.zip) inside the CTAN archive
packtdszip = true

-- All *.eps (including the demo figure hithesis-golfer.eps and the donation
-- QR hithesis-zfb.eps) are installed to tex/latex/hithesis/ so that the
-- example templates can \includegraphics them directly.

-- Ship the example templates' source in the TDS doc tree. hithesis.ins now
-- only generates the runtime files into the current directory (not into
-- examples/), so the examples/ tree in the repo is already source-only; the
-- docinit_hook below still strips .gitkeep/Makefile/latexmkrc and any stale
-- generated files to satisfy pkgcheck (E0005/E0007/E0019).
tdsdirs = {
  ["build/examples"] = "doc/latex/hithesis/examples",
}

-- ---------------------------------------------------------------------------
-- Documentation typesetting
--
-- The .dtx displays the example templates with
--   \lstinputlisting{examples/hitbook/.../thesis.tex}
-- so the example tree must be present in the typeset directory. l3build's own
-- file copy flattens subdirectories, hence this hook copies the tree verbatim.
-- ---------------------------------------------------------------------------
function docinit_hook()
  local errorlevel = cp("examples", sourcefiledir, typesetdir)
  if errorlevel ~= 0 then
    return errorlevel
  end

  -- Build a source-only copy of the examples for the CTAN archive.
  errorlevel = cp("examples", sourcefiledir, builddir)
  if errorlevel ~= 0 then
    return errorlevel
  end

  -- Remove .gitkeep, build scripts, and files regenerated by hithesis.ins
  -- from that copy, so only LaTeX sources (.tex/.bib/.bst/.pdf) remain.
  local find_cmd = "find '" .. builddir .. "/examples' -type f \\( " ..
    "-name '.gitkeep' -o -name 'Makefile' -o -name 'latexmkrc' " ..
    "-o -name '*.cls' -o -name '*.cfg' -o -name '*.sty' -o -name '*.ist' " ..
    "-o -name '*.eps' -o -name 'hithesis.bst' -o -name 'hitszthesis.bst' \\) " ..
    "-delete"
  return run(".", find_cmd) and 0 or 1
end

-- ---------------------------------------------------------------------------
-- Version tagging
--
--   l3build tag v3.2.1 --date 2026-10-08
--
-- updates the two \Provides... lines in hithesis.dtx. The version is stored
-- once without the leading "v" (the .dtx driver line) and once with it (the
-- shared guard line used by the generated .cls/.cfg files).
-- ---------------------------------------------------------------------------
function update_tag(file, content, tagname, tagdate)
  if file ~= "hithesis.dtx" then
    return content
  end
  local version = (tagname or ""):gsub("^v", "")            -- v3.2.1 -> 3.2.1
  local date    = (tagdate or os.date("%Y-%m-%d")):gsub("%-", "/")

  -- \ProvidesFile{hithesis.dtx}[0000/00/00 3.1e Harbin Institute ...]
  content = content:gsub(
    "\\ProvidesFile{hithesis%.dtx}%[([^%]]*)%]",
    function(inner)
      local _, _, desc = (inner or ""):match("^(%S+)%s+(%S+)%s+(.*)$")
      desc = desc or "Harbin Institute of Technology Thesis Template"
      return "\\ProvidesFile{hithesis.dtx}[" .. date .. " " .. version
        .. " " .. desc .. "]"
    end
  )

  -- %<...>[0000/00/00 v3.1e Harbin Institute of Technology Thesis Template]
  content = content:gsub(
    "(%[)[^%]]* v[^ ]+ (Harbin Institute of Technology Thesis Template%])",
    "%1" .. date .. " v" .. version .. " %2"
  )
  return content
end

function tag_hook(tagname, tagdate)
  print("hithesis set to " .. (tagname or "?") .. " (" .. (tagdate or "?") .. ")")
  return 0
end

-- ---------------------------------------------------------------------------
-- CTAN upload metadata
--
--   l3build ctan                     # build hithesis-ctan.zip
--   l3build upload --dry-run         # validate the archive only
--   l3build upload v3.2.1            # validate, then ask before uploading
--   l3build upload v3.2.1 \
--     --message "..." --email you@example.com
--
-- The announcement defaults to RELEASE_NOTES.md (generated by `make changes`)
-- and can be overridden with --message or --file.
--
-- By default `l3build upload` asks for confirmation before posting to CTAN.
-- Set the CTAN_UPLOAD environment variable to "true" to upload non-interactively
-- (used by the GitHub Actions workflow on a version bump). Locally the prompt
-- is kept unless this variable is set.
-- ---------------------------------------------------------------------------
if os.getenv("CTAN_UPLOAD") == "true" then
  ctanupload = true
end

local function dtx_version()
  local f = assert(io.open("hithesis.dtx", "r"))
  local content = f:read("*a")
  f:close()
  local inner = content:match("\\ProvidesFile{hithesis%.dtx}%[([^%]]*)%]")
  local _, version = (inner or ""):match("^(%S+)%s+(%S+)")
  return version or "0.0.0"
end

uploadconfig = {
  -- Mandatory fields
  pkg        = "hithesis",
  author     = "Chu Yanshuo",
  uploader   = "Chu Yanshuo",
  email      = "yanshuoc@gmail.com",
  summary    = "Harbin Institute of Technology Thesis Template",
  license    = "lppl1.3a",
  version    = dtx_version(),
  -- NOTE: verify this against your CTAN entry. hithesis was historically
  -- published under /macros/xetex/latex/hithesis; CTAN keeps the existing
  -- location for updates, so changing to /macros/latex/contrib/hithesis has
  -- to be arranged with the CTAN team.
  ctanPath   = "/macros/latex/contrib/hithesis",

  -- Optional fields
  description = [[
    hithesis is a LaTeX thesis template package for Harbin Institute of
    Technology (all three campuses) supporting bachelor, master and doctor
    dissertations, postdoc reports, thesis proposals and midterm reports,
    in both Chinese and English.
  ]],
  home        = "https://github.com/hithesis/hithesis",
  repository  = "https://github.com/hithesis/hithesis",
  support     = "https://github.com/hithesis/hithesis/issues",
  bugtracker  = "https://github.com/hithesis/hithesis/issues",
  development = "https://github.com/hithesis/hithesis",
  topic       = {"dissertation", "class", "xetex", "chinese"},
  update      = true,

  announcement_file = "RELEASE_NOTES.md",
}
