# Makefile for hithesis

METHOD = xelatex
LATEXMKOPTS = -xelatex

PACKAGE = hithesis
VERSION = `grep -m 1 -o "v[0-9]\+\.[0-9]\+\.[0-9]\+" $(PACKAGE).dtx`

SOURCES = $(PACKAGE).ins $(PACKAGE).dtx

# Runtime files generated by `latex hithesis.ins` into the current directory.
CLS = $(PACKAGE)book.cls $(PACKAGE)art.cls $(PACKAGE)artplus.cls
CFG = $(PACKAGE)book.cfg $(PACKAGE)art.cfg
STY = $(PACKAGE).sty dtx-style.sty
BST = $(PACKAGE).bst hitszthesis.bst
IST = $(PACKAGE).ist
EPS = $(PACKAGE)-logo.eps $(PACKAGE)-bthesistitle.eps \
      $(PACKAGE)-shenzhenbthesistitle.eps $(PACKAGE)-zfb.eps \
      $(PACKAGE)-hrb-bachelor-bottommark.eps $(PACKAGE)-golfer.eps

TARGETS = $(CLS) $(CFG) $(STY) $(BST) $(IST) $(EPS)

# Runtime files copied into each example folder by `make examples`.
HITBOOK = $(PACKAGE)book.cls $(PACKAGE)book.cfg $(PACKAGE).sty \
          $(PACKAGE).bst hitszthesis.bst \
          $(PACKAGE)-logo.eps $(PACKAGE)-bthesistitle.eps \
          $(PACKAGE)-shenzhenbthesistitle.eps $(PACKAGE)-zfb.eps \
          $(PACKAGE)-hrb-bachelor-bottommark.eps
REPORTS = $(PACKAGE)art.cls $(PACKAGE)art.cfg $(PACKAGE).bst hitszthesis.bst \
          $(PACKAGE)-logo.eps $(PACKAGE)-bthesistitle.eps $(PACKAGE)-zfb.eps \
          $(PACKAGE)-hrb-bachelor-bottommark.eps
REPORTPLUS = $(PACKAGE)artplus.cls $(PACKAGE)art.cfg $(PACKAGE).bst \
             hitszthesis.bst $(PACKAGE)-logo.eps $(PACKAGE)-bthesistitle.eps \
             $(PACKAGE)-zfb.eps
GOLFER = $(PACKAGE)-golfer.eps

# Example folders.
EX_CHINESE = examples/hitbook/chinese
EX_ENGLISH = examples/hitbook/english
EX_REPORTS = examples/hitart/reports
EX_REPORTPLUS = examples/hitart/reportplus

# All files copied into examples (for `make clean`).
EX_COPY = $(addprefix $(EX_CHINESE)/,$(HITBOOK) $(PACKAGE).ist) \
          $(addprefix $(EX_ENGLISH)/,$(HITBOOK)) \
          $(addprefix $(EX_REPORTS)/,$(REPORTS)) \
          $(addprefix $(EX_REPORTPLUS)/,$(REPORTPLUS)) \
          $(addprefix $(EX_CHINESE)/figures/,$(GOLFER)) \
          $(addprefix $(EX_ENGLISH)/figures/,$(GOLFER)) \
          $(addprefix $(EX_REPORTS)/figures/,$(GOLFER)) \
          $(addprefix $(EX_REPORTPLUS)/figures/,$(GOLFER))

CHANGE_RAW = .changes.raw
RELEASE_NOTES = RELEASE_NOTES.md

ifdef SystemRoot
	RM = del /Q
	OPEN = start
else
	RM = rm -f
	OPEN = open
endif

.PHONY: all cls examples doc viewdoc dist auxclean clean distclean changes version-changes
.PHONY: ctan upload l3unpack l3doc l3install l3tag l3clean

all: doc

cls: $(TARGETS)

$(TARGETS): $(SOURCES)
	latex $(PACKAGE).ins

examples: $(TARGETS)
	cp $(HITBOOK) $(PACKAGE).ist $(EX_CHINESE)/
	cp $(HITBOOK) $(EX_ENGLISH)/
	cp $(REPORTS) $(EX_REPORTS)/
	cp $(REPORTPLUS) $(EX_REPORTPLUS)/
	cp $(GOLFER) $(EX_CHINESE)/figures/
	cp $(GOLFER) $(EX_ENGLISH)/figures/
	cp $(GOLFER) $(EX_REPORTS)/figures/
	cp $(GOLFER) $(EX_REPORTPLUS)/figures/

doc: $(PACKAGE).pdf

viewdoc: doc
	$(OPEN) $(PACKAGE).pdf

ifeq ($(METHOD),latexmk)

$(PACKAGE).pdf: $(TARGETS)
	$(METHOD) $(LATEXMKOPTS) $(PACKAGE).dtx

else ifeq ($(METHOD),xelatex)

$(PACKAGE).pdf: $(TARGETS)
	$(METHOD) $(PACKAGE).dtx
	makeindex -s gind.ist -o $(PACKAGE).ind $(PACKAGE).idx
	makeindex -s gglo.ist -o $(PACKAGE).gls $(PACKAGE).glo
	$(METHOD) $(PACKAGE).dtx
	$(METHOD) $(PACKAGE).dtx

else
$(error Unknown METHOD: $(METHOD))
endif

dist: all
	-$(RM) $(PACKAGE)-$(VERSION).zip
	zip -r $(PACKAGE)-$(VERSION).zip examples/ $(PACKAGE).pdf

auxclean:
	latexmk -c $(PACKAGE).dtx
	-$(RM) *.glo *.gls *.hd

clean: auxclean
	-$(RM) $(TARGETS)
	-$(RM) $(EX_COPY)
	-$(RM) $(PACKAGE).pdf
	-$(RM) $(CHANGE_RAW) $(RELEASE_NOTES)
	-$(RM) $(PACKAGE)-ctan.zip $(PACKAGE).tds.zip

distclean: clean
	-$(RM) $(PACKAGE)-$(VERSION).zip
	-git clean -fdX

# -------------------------------
# l3build integration
# See build.lua and the README for the full workflow.
# -------------------------------

l3unpack:
	l3build unpack

l3doc:
	l3build doc

l3install:
	l3build install --full

ctan:
	l3build ctan

upload:
	l3build upload

l3tag:
	l3build tag

l3clean:
	l3build clean

# -------------------------------
# Extract \changes{} from .dtx
# -------------------------------

$(CHANGE_RAW): $(PACKAGE).dtx
	@awk '/\\changes\{/ { \
	  line = $$0; \
	  match(line, /\\changes\{([^}]*)\}\{([^}]*)\}\{/, a); \
	  if (a[1] != "") { \
	    ver = a[1]; \
	    date = a[2]; \
	    gsub(/^v/, "", ver); \
	    sub(/.*\\changes\{[^}]*\}\{[^}]*\}\{/, "", line); \
	    depth = 1; txt = ""; \
	    for (i = 1; i <= length(line); i++) { \
	      c = substr(line, i, 1); \
	      if (c == "{") depth++; \
	      if (c == "}") depth--; \
	      if (depth == 0) break; \
	      txt = txt c; \
	    } \
	    print ver "|" date "|" txt; \
	  } \
	}' $< > $@

$(RELEASE_NOTES): $(CHANGE_RAW)
	@latest=$$(cut -d'|' -f1 $< | sort -V | uniq | tail -n1); \
	echo "## v$$latest" > $@; \
	echo >> $@; \
	echo "This release of hithesis (the Harbin Institute of Technology thesis" >> $@; \
	echo "template for all three campuses) includes the following changes:" >> $@; \
	echo >> $@; \
	awk -F'|' -v v="$$latest" '$$1 == v { \
	  printf "- %s (%s)\n", $$3, $$2 \
	}' $< | sort -k2 | uniq >> $@

changes: $(RELEASE_NOTES)
	@echo "Release notes generated: $(RELEASE_NOTES)"

version-changes: $(CHANGE_RAW)
	@cut -d'|' -f1 $< | sort -V | uniq | tail -n1 | sed 's/^/v/'
