# vim: set ft=perl:
# 对拍件的 latexmk 配置：lualatex、成果页那一次 bibtex 跟着主 bibtex 跑、范例没有索引
@default_files = ('main.tex');
$pdf_mode = 4;
$bibtex_use = 2;
$bibtex = 'internal hit_pub_bibtex';
sub hit_pub_bibtex {
   my $ret = system( "bibtex", $$Psource );
   my $pub = $$Psource;
   $pub =~ s/\.aux$//;
   $pub .= "-pub";
   if ( -e "$pub.aux" ) { system( "bibtex", $pub ); }
   return $ret;
}
$makeindex = 'internal noindex';
sub noindex {
   open( my $f, '>', $$Pdest ); close $f;
   return 0;
}
$clean_ext = "synctex.gz aux bbl blg fdb_latexmk idx ilg ind lof log lot out run.xml toc thm toe pdf";
$lualatex = "lualatex -file-line-error -interaction=nonstopmode -halt-on-error %O %S";
